import { Nunito } from "next/font/google";

import "remixicon/fonts/remixicon.css";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} bg-gray-100`}>{children}</body>
    </html>
  );
}
